---
type: library
name: zurborg/enum-generator

description: 'Zero-dependency enumeration class code generator'
license: ISC
keywords: []

authors:
  - name: David Zurborg
    email: zurborg@cpan.org
    homepage: https://zurborg.github.io/

require:
  php: '^7.4'
  zurborg/wrap-json: '^1.0'

require-dev:
  phpunit/phpunit: '~9'
  squizlabs/php_codesniffer: '~3'

minimum-stability: stable

autoload:
  psr-4:
    Enum\: src/

autoload-dev:
  psr-4:
    '': tests/generated/

bin:
  - bin/enum-generator

archive:
  exclude:
    - '.*'
    - '*~'
    - vendor/
    - Makefile
    - composer.lock
    - composer.phar
    - composer.yaml
